context.modules = [
	{
		name = "libpipewire-module-filter-chain"
		args = {
			node.description = "Apple EarPods Parametric EQ"
			node.passive = true
			filter.graph = {
				nodes = [
					{
						type = builtin
						name = earpods_eq
						label = param_eq
						config = {
							filename = "/home/finn/.config/pipewire/earpods.txt"
						}
					}
					{
						type = builtin
						name = post_gain_left
						label = linear
						control = { "Mult" = 5.8884 }
					}
					{
						type = builtin
						name = post_gain_right
						label = linear
						control = { "Mult" = 5.8884 }
					}
					{
						type = ladspa
						name = limiter
						plugin = fast_lookahead_limiter_1913
						label = fastLookaheadLimiter
						control = {
							"Limit (dB)" = -1.0
							"Release Time (s)" = 0.2
						}
					}
				]
				links = [
					{ output = "earpods_eq:Out 1" input = "post_gain_left:In" }
					{ output = "earpods_eq:Out 2" input = "post_gain_right:In" }
					{ output = "post_gain_left:Out" input = "limiter:Input 1" }
					{ output = "post_gain_right:Out" input = "limiter:Input 2" }
				]
				inputs = [ "earpods_eq:In 1" "earpods_eq:In 2" ]
				outputs = [ "limiter:Output 1" "limiter:Output 2" ]
			}
			capture.props = {
				node.name = "earpods_input"
				node.passive = true
				media.class = "Audio/Sink"
				audio.channels = 2
				audio.position = [ FL FR ]
			}
			playback.props = {
				node.name = "earpods_output"
				node.passive = true
				target.object = "alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH502607BNL1MQAM-00.analog-stereo"
			}
		}
	}
]
