import = ["~/.config/alacritty/dracula.toml"]

[window]
dynamic_padding = true

[font]
size = 6.5

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Plus"
mods = "Alt"

[[colors.indexed_colors]]
color = "#6272A4"
index = 61

[[colors.indexed_colors]]
color = "#50FA7B"
index = 84

[[colors.indexed_colors]]
color = "#8BE9FD"
index = 117

[[colors.indexed_colors]]
color = "#BD93F9"
index = 141

[[colors.indexed_colors]]
color = "#FF5555"
index = 203

[[colors.indexed_colors]]
color = "#FF79C6"
index = 212

[[colors.indexed_colors]]
color = "#FFB86C"
index = 215

[[colors.indexed_colors]]
color = "#F1FA8C"
index = 228

[[colors.indexed_colors]]
color = "#191A21"
index = 234

[[colors.indexed_colors]]
color = "#21222C"
index = 235

[[colors.indexed_colors]]
color = "#282A36"
index = 236

[[colors.indexed_colors]]
color = "#343746"
index = 237

[[colors.indexed_colors]]
color = "#424450"
index = 238

[[colors.indexed_colors]]
color = "#424450"
index = 238

[[colors.indexed_colors]]
color = "#44475A"
index = 239

[[colors.indexed_colors]]
color = "#F8F8F2"
index = 253
